export const API_BASE_URL = "http://74.248.139.184:8000";

const AUTH_BASE = `${API_BASE_URL}/auth`;

const COUNTRIES_BASE = `${API_BASE_URL}/countries`;
const COUNTRIES_CAPITALS_BASE = `${COUNTRIES_BASE}/capitals`

const QUIZ_BASE = `${API_BASE_URL}/quiz`;

export const AUTH_ENDPOINTS = {
  LOGIN: `${AUTH_BASE}/login`,
  REGISTER: `${AUTH_BASE}/register`,
  ME: `${AUTH_BASE}/me`
}

export const FLAGS_ENDPOINTS = {
  ALL_FLAGS: `${COUNTRIES_BASE}`,
  AFRICAN_FLAGS: `${COUNTRIES_BASE}/africa`,
  ASIAN_FLAGS: `${COUNTRIES_BASE}/asia`,
  AUSTRALIAN_FLAGS: `${COUNTRIES_BASE}/australia`,
  EUROPEAN_FLAGS: `${COUNTRIES_BASE}/europe`,
  NORTH_AMERICAN_FLAGS: `${COUNTRIES_BASE}/north-america`,
  SOUTH_AMERICAN_FLAGS: `${COUNTRIES_BASE}/south-america`,
};

export const CAPITALS_ENDPOINTS = {
  ALL_CAPITALS: `${COUNTRIES_CAPITALS_BASE}`,
  AFRICAN_CAPITALS: `${COUNTRIES_CAPITALS_BASE}/africa`,
  ASIAN_CAPITALS: `${COUNTRIES_CAPITALS_BASE}/asia`,
  AUSTRALIAN_CAPITALS: `${COUNTRIES_CAPITALS_BASE}/australia`,
  EUROPEAN_CAPITALS: `${COUNTRIES_CAPITALS_BASE}/europe`,
  NORTH_AMERICAN_CAPITALS: `${COUNTRIES_CAPITALS_BASE}/north-america`,
  SOUTH_AMERICAN_CAPITALS: `${COUNTRIES_CAPITALS_BASE}/south-america`,
};

export const QUIZ_ENDPOINTS = {
  MY_BEST: `${QUIZ_BASE}/my-best`,
  LEADERBOARD: `${QUIZ_BASE}/leaderboards`,
  SUBMIT: `${QUIZ_BASE}/submit`,
}